# POST request data to filter retrieved BOPZ documents

DATA_POST = {
	'numPag': '',
	'idProcedente': '8610',
	'idPortador': '',
	'hProcedente': ' AYUNTAMIENTO DE ZARAGOZA',
	'hPortador': '',
	'idPagadora': '8610',
	'hPagadora': ' AYUNTAMIENTO DE ZARAGOZA',
	'primeraVez': 'N',
	'ficheroDoc': 'N',
	'numRegistroInf': '',
	'numRegistroSup': '',
	'esPortalSN': 'S',
	'numBoletinInf': '',
	'numRegistroNumInf': '',
	'numRegistroAnyoInf': '',
	'numRegistroNumSup': '',
	'numRegistroAnyoSup': '',
	'numBoletinAuxInf': '',
	'anyoBoletinInf': '',
	'numBoletinSup': '',
	'anyoBoletinSup': '',
	'fechaPubInf': '',
    'fechaPubSup': '',
	'procedente': ' AYUNTAMIENTO DE ZARAGOZA',
	'tematica': '',
	'titulo': '',
	'contenido': ''
}